extern struct massive burnstage;
extern struct massive firststage;
extern struct massive secondstage;
extern struct massive thirdstage;
extern struct massive temperature_averaging_massive;
extern unsigned int result;
extern int zerostage;
extern int coefficent;
extern int zerolevelavg;
extern int celllevelavg;
extern int celltempavg;
extern int tick;
extern char sd_init;
extern char webpage[1000];
extern unsigned int len;