extern sfr sbit SPI_Ethernet_Rst;
extern sfr sbit SPI_Ethernet_CS;
extern sfr sbit SPI_Ethernet_Rst_Direction;
extern sfr sbit SPI_Ethernet_CS_Direction;
extern sfr sbit AD7707_DRDY;
extern sfr sbit AD7705_CS;
extern sfr sbit LED0;
extern sfr sbit LED0_Direction;
extern sfr sbit LED0_Toggle;
